### ISSUE TITLE
[Suggestion] Config Cleanup

### ISSUE THREAD

**Issue by BroCrows** [WolfDen133/FormCreator-NEW-#1]
Remove the spaces pls
or can I do this myself without it crashing(idk I haven't downloaded the newer one yet)

**Comment by WolfDen133** [comment]
Hey William, what do you mean by 'spaces'

**Comment by WolfDen133** [comment]
The spaces are for ease of viewing for inexperienced players, all blank lines and comments (all the text after a # for a given line) can be removed with no issues

**Comment by BroCrows** [comment]
Ok
