### ISSUE TITLE
Wildcards not updating

### ISSUE THREAD

**Issue by KygekDev** [WolfDen133/FormCreator-NEW-#4]
In the example form, it showed there is 0 player in the server.

![image](https://user-images.githubusercontent.com/68368066/121790451-10e73e80-cc12-11eb-84c9-7797d2a4bef9.png)

This behavior is expected due to an issue in the code:

https://github.com/WolfDen133/FormCreator/blob/83ae258f9338477a1e5816d90255476349853510/src/WolfDen133/FormCreator/FormCreator.php#L88

Wildcards should be loaded every time a form is send to a player, not loaded only once when the server is starting.

**Comment by WolfDen133** [comment]
Hey KygekDev, could you posibly add me on my discord so we can talk more directly my, you can add me [here](https://dsc.bio/WolfDen133), I am awere of this issue and am in the process of fixing it, I'm still trying to figure out how to keep the `registerWildCard()` function for custom wild-cards, but am having some issues, any help would be great, Thanks.

**Comment by KygekDev** [comment]
Sent a friend request to you. My Discord account is KygekDev#6415.

**Comment by WolfDen133** [comment]
Thank you, Ill talk a little later because I have school now. :)

**Comment by KygekDev** [comment]
No problem!

**Comment by WolfDen133** [comment]
This issue has no been fixed in the latest version.
