### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by xKurt** [WolfDen133/FormCreator-NEW-#5]
Hi,
The plugin already has the {LEVEL_PLAYERS} which only shows the world you are currently in. But I think it would be nice to add a wild card with the player count on the specific world too.
So, Is it possible to implement a wild card that will show a player count in a specific world?
Thanks!

**Comment by WolfDen133** [comment]
Yes, of course it is, you can add your own wildcards branching the plugin, and adding them in the function getWildcards()
